spring.application.name=@project.artifactId@
debug=true

server.address=0.0.0.0
server.http2.enabled=true

logging.file.name=target/entityresolver-issues.log
logging.include-application-name=false

# log all GeoTools
logging.level.org.geotools=DEBUG
logging.level.nl.b3partners.entityresolverissues=DEBUG