spring.application.name=@project.artifactId@
#debug=true

server.address=0.0.0.0
server.http2.enabled=true

logging.file.name=target/entityresolver-issues.log
logging.include-application-name=false

logging.level.org.geotools=DEBUG
logging.level.org.geotools.data.util=INFO
logging.level.org.geotools.referencing.factory=WARN
logging.level.org.geotools.factory=WARN
logging.level.org.geotools.util.factory=WARN
logging.level.org.geotools.referencing=WARN
logging.level.nl.b3partners.entityresolverissues=DEBUG