name: Maven Build
env:
  MAVEN_OPTS: -Djava.awt.headless=true
  JAVA_VERSION: '17'

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: 'Set up JDK'
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'
      - name: 'Build with Maven'
        run: mvn install -DskipTests=true

  test_one:
    name: 'Run JUnit test with Maven'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: 'Set up JDK'
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'
      - name: 'Run WFSGetFeatureUtilTest'
        run: mvn test -Dtest=WFSGetFeatureUtilTest

  test_two:
    name: 'Run Spring Boot test with Maven'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: 'Set up JDK'
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'
      - name: 'Run WFSGetFeatureControllerTest'
        run: mvn test -Dtest=WFSGetFeatureControllerTest